/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fmtech_ffmpeg_VideoUtils */

#ifndef _Included_com_fmtech_ffmpeg_VideoUtils
#define _Included_com_fmtech_ffmpeg_VideoUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fmtech_ffmpeg_VideoUtils
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fmtech_ffmpeg_VideoUtils_decode
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
