/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fmtech_ffmpeg_FMPlayer */

#ifndef _Included_com_fmtech_ffmpeg_FMPlayer
#define _Included_com_fmtech_ffmpeg_FMPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fmtech_ffmpeg_FMPlayer
 * Method:    render
 * Signature: (Ljava/lang/String;Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_fmtech_ffmpeg_FMPlayer_render
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
