/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fmtech_update_ApkDiff */

#ifndef _Included_com_fmtech_update_ApkDiff
#define _Included_com_fmtech_update_ApkDiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fmtech_update_ApkDiff
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fmtech_update_ApkDiff_diff
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
