/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fmtech_incrementalupdate_BsPatch */

#ifndef _Included_com_fmtech_incrementalupdate_BsPatch
#define _Included_com_fmtech_incrementalupdate_BsPatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fmtech_incrementalupdate_BsPatch
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fmtech_incrementalupdate_BsPatch_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
